[project]
name = "ll-brain-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "paho-mqtt>=2.1.0",
    "python-osc",
    "stupidartnet>=1.6.0",
]
